#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

build=../build/ios
build_headers=$build/headers

rm -rf $build
mkdir -p $build
mkdir -p $build_headers

soomla-native/projects/cocos2dx-ios-profile/build_all

cp -RL submodules/ios-profile/build/* $build/
cp -RL soomla-native/projects/cocos2dx-ios-profile/build/* $build/

cp -L submodules/ios-profile/build/libSoomlaiOSProfile.a $build/
cp -RL submodules/ios-profile/build/headers/SoomlaiOSProfile $build_headers/
cp -RL submodules/ios-profile/build/ios-profile-facebook $build/
cp -RL submodules/ios-profile/build/ios-profile-google $build/
cp -RL submodules/ios-profile/build/ios-profile-twitter $build/

cd - > /dev/null
