#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

build=../build/ios
build_headers=$build/headers

rm -rf $build
mkdir -p $build
mkdir -p $build_headers

soomla-native/projects/cocos2dx-ios-profile/build_all

cp -RL submodules/ios-profile/build/* $build/
cp -RL soomla-native/projects/cocos2dx-ios-profile/build/* $build/

cd - > /dev/null
