#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

build=../build/android

rm -rf $build
mkdir -p $build

soomla-native/projects/cocos2dx-android-profile/build_all

cp -RL submodules/android-profile/build/* $build/
cp -RL soomla-native/projects/cocos2dx-android-profile/build/* $build/

# handle special case of build_all location for android-profile
cp -L submodules/android-profile/build/AndroidProfile.jar $build/
cp -L submodules/android-profile/build/simple-fb-*.jar $build/
cp -L submodules/android-profile/build/gson-*.jar $build/
cp -L submodules/android-profile/build/AndroidProfileFacebook.jar $build/
cp -L submodules/android-profile/build/AndroidProfileGoogle.jar $build/
cp -L submodules/android-profile/build/AndroidProfileTwitter.jar $build/
cp -L submodules/android-profile/build/twitter4j-asyc-*.jar $build/
cp -L submodules/android-profile/build/twitter4j-core-*.jar $build/

cd - > /dev/null
