#ifndef _Cocos2dxSoomla_H
#define _Cocos2dxSoomla_H

#include "domain/rewards/CCAggregateReward.h"
#include "domain/rewards/CCBadgeReward.h"
#include "domain/rewards/CCRandomReward.h"
#include "domain/rewards/CCReward.h"
#include "domain/rewards/CCSequenceReward.h"
#include "domain/rewards/CCVirtualItemReward.h"
#include "domain/CCDomain.h"
#include "domain/CCUserProfile.h"
#include "CCProfileEventHandler.h"
#include "CCIStoreAssets.h"
#include "CCLifetimeVG.h"
#include "CCMarketItem.h"
#include "CCNonConsumableItem.h"
#include "CCPurchasableVirtualItem.h"
#include "CCPurchaseType.h"
#include "CCPurchaseWithMarket.h"
#include "CCPurchaseWithVirtualItem.h"
#include "CCSingleUsePackVG.h"
#include "CCSingleUseVG.h"
#include "CCProfileError.h"
#include "CCProfileEventDispatcher.h"
#include "CCProfileNdkBridge.h"
#include "CCProfileController.h"
#include "CCStoreInfo.h"
#include "CCStoreInventory.h"
#include "CCStoreUtils.h"
#include "CCUpgradeVG.h"
#include "CCVirtualCategory.h"
#include "CCVirtualCurrency.h"
#include "CCVirtualCurrencyPack.h"
#include "CCVirtualGood.h"
#include "CCVirtualItem.h"

#endif /* !_Cocos2dxSoomla_H */
